apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.team }}-pdb
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels: {{ toYamlPretty .Values.labels | nindent 6 }}