team: frontend
environment: prod
labels:
  app: voting
  component: vote
  env: prod
  team: frontend
aws:
  accountId: "AWS_ACCOUNT_ID_REDACTED"
  region: us-east-1
securityContext:
  runAsGroup: 999 #appgroup
  runAsNonRoot: true
  runAsUser: 999 #appuser
  fsGroup: 999
image:
  name: voting-vote
  tag: 93bc21942bd50c099f8679b9571ba3cf0fd826ad
ports:
  - containerPort: 80
envFrom: #[]
  - configMapRef:
      name: redis-connection
env:
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis-secret
        key: password
gateway:
  name: pub-gateway
  namespace: platform-prod
service:
  port:
    number: 8080
    name: web
  type: ClusterIP ##For IP Target Type
  targetPort: 80
  protocol: TCP
httpRoute:
  rules:
    matches:
      - path:
          type: PathPrefix
          value: /vote
    filters: []
targetGroup:
  path: /vote
metrics:
  path: /metrics
scaling:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
resources:
  requests:
    cpu: "0.25"
    memory: "0.35Gi"
pdb:
  minAvailable: 1
livenessProbe:
  httpGet:
    path: /vote
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 20
readinessProbe:
  httpGet:
    path: /vote
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 20
  failureThreshold: 6
  