apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: {{ .Values.team }}-{{ .Values.environment }}
  labels: {{ toYamlPretty .Values.labels | nindent 4 }}
  name: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  selector:
    matchLabels: {{ toYamlPretty .Values.labels | nindent 6 }}
  strategy:
    blueGreen:
      activeService: {{ .Chart.Name }}-service
      previewService: {{ .Chart.Name }}-preview-service
      autoPromotionEnabled: false
      previewReplicaCount: 1
  template:
    metadata:
      labels: {{ toYamlPretty .Values.labels | nindent 8 }}
    spec:
      securityContext: {{ toYamlPretty .Values.securityContext | nindent 8 }}
      resources: {{ toYamlPretty .Values.resources | nindent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: team
                operator: In
                values:
                  - {{ .Values.team }}
      serviceAccountName: {{ .Chart.Name}}-sa
      containers:
        - image: {{ .Values.aws.accountId }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com/{{ .Values.image.name }}:{{ .Values.image.tag }}
          name: {{ .Values.image.name }}
          {{- with .Values.ports }}
          ports: {{- toYamlPretty . | nindent 12 -}}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom: {{- toYamlPretty . | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env: {{ toYamlPretty . | nindent 12 }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
          {{- with .Values.livenessProbe }}
          livenessProbe: {{ . | toYamlPretty | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe: {{ . | toYamlPretty | nindent 12 }}
          {{- end }}

            
