apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name}}-service-monitor
  labels: ##release needed so prometheus picks up the ServiceMonitor
    release: kube-prometheus-stack-prod {{ toYamlPretty .Values.labels | nindent 4 }}
spec:
  selector:
    matchLabels: {{ toYamlPretty .Values.labels | nindent 6 }}
  endpoints:
    - port: {{ .Values.service.port.name }}
      path: {{ .Values.metrics.path }}