{{- if not (eq .Values.targetGroup.path "/") }}
apiVersion: gateway.k8s.aws/v1
kind: TargetGroupConfiguration
metadata:
  name: {{ .Chart.Name }}-tg-config
  namespace: {{ .Values.team }}-{{ .Values.environment }}
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  targetReference:
    name: {{ .Chart.Name }}-service
  defaultConfiguration:
    healthCheckConfig:
      healthCheckPath: {{ .Values.targetGroup.path }} ##Expects health check at that path
      healthyThresholdCount: 2
      healthCheckInterval: 30
      unhealthyThresholdCount: 3
      healthCheckTimeout: 15
{{- end -}}