apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.redisExternalSecret.name }}
  namespace: {{ .Values.team }}-{{ .Values.environment }}
spec:
  refreshPolicy: OnChange
  target:
    name: {{ .Values.redisExternalSecret.name }}
    # keep the Secret if this redisExternalSecret is ever deleted
    creationPolicy: Orphan
    # never rewrite the Secret data once it exists, even on recreation
    immutable: false
  dataFrom:
    # This grabs EVERY secret key value pair under the specified secret.
    - extract:
        key: {{ .Values.redisExternalSecret.name }}
      sourceRef:
        storeRef:
          name: {{ .Values.redisExternalSecret.storeRef }}
          kind: ClusterSecretStore