apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.redisExternalParameter.name }}
  namespace: {{ .Values.team }}-{{ .Values.environment }}
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: {{ .Values.redisExternalParameter.storeRef }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.redisExternalParameter.name }}
    manifest:
      apiVersion: v1
      kind: ConfigMap ##Creates a configmap instead of a secret
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: {{ .Values.redisExternalParameter.name }}
        conversionStrategy: Default
        decodingStrategy: Auto