team: frontend
environment: prod
labels:
  component: global
  env: prod
  team: frontend
aws:
  accountId: "AWS_ACCOUNT_ID_REDACTED"
  region: us-east-1
redisExternalSecret:
  name: redis-secret
  storeRef: prod-clusterSecretStore_secrets_manager ##Secret Store Ref to use
redisExternalParameter:
  name: redis-connection
  storeRef: prod-clusterSecretStore_parameter_store ##Secret Store Ref to use
postgresExternalParameter:
  name: postgres-connection
  storeRef: prod-clusterSecretStore_parameter_store ##Secret Store Ref to use
postgresExternalSecret:
  name: db-admin-backend-credentials
  storeRef: prod-clusterSecretStore_secrets_manager ##Secret Store Ref to use